---
deploymentservers:
  hosts:
    deployment1:
      ansible_host: deployment-it21992.ddns.net
      ansible_port: 22
      ansible_ssh_user: it21992
  vars:
    ansible_python_interpreter: /usr/bin/python3
database:
  hosts:
    deployment1:
      ansible_host: deployment-it21992.ddns.net
      ansible_port: 22
      ansible_ssh_user: it21992
  vars:
    ansible_python_interpreter: /usr/bin/python3
